import type { Metadata } from "next";
import Navbar from "./components/navbar";
import "./globals.css";



export const metadata: Metadata = {
  title: "Day01",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body className="bg-green-200">
        <Navbar/>
        
       <main >{children}</main>
      </body>
    </html>
  );
}
