import type { Metadata } from "next";
import Navbar from "./components/navbar";
import "./globals.css";
import Footer from "./components/footer";



export const metadata: Metadata = {
  title: "Day01",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body className="bg-green-200">
        <Navbar/>
        
       <main className="mx-auto max-w-7xl pt-4  h-screen">{children}</main>
       <Footer/>
      </body>
    </html>
  );
}
